### home
GET {{api_base}}/

### health-check
GET {{api_base}}/health-check

### advice 
POST {{api_base}}/advice
Content-Type: application/json

{
  "birthdate": "10/05/1990"
}

### send-notification 
POST {{api_base}}/send-notification
